name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clona la repository
        uses: actions/checkout@v2

      - name: Imposta Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Installa le dipendenze
        run: npm install

      - name: Esegui i test
        run: npm test

      - name: Esegui la build dell'eseguibile
        run: npm run build --if-present

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Effettua il Login su Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Builda e pusha l'immagine su Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/libri-api:latest